server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /client # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    upload-service:
      path: /upload/**
      serivceId: upload-service
      strip-prefix: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长 5000ms
ribbon:
  ConnectionTimeout: 1000 # ribbon连接超时时长
  ReadTimeout: 3500 # 读取超时时长
  MaxAutoRetries: 0 # 服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数