server:
  port: 8083
spring:
  application:
    name: search-service
  rabbitmq:
    host: 192.168.198.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.198.128:9300
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2?serverTimezone=UTC
    username: root
    password: 763081703
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期