server:
  port: 8085
spring:
  application:
    name: user-service
  redis:
    host: 192.168.198.128
  rabbitmq:
    host: 192.168.198.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2?serverTimezone=UTC
    username: root
    password: 763081703
    # driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo